
# [theme]
# name = "custom_github_dark_tritanopia"
# path = "./themes/custom_github_dark_tritanopia"

theme = "github_dark_dimmed"

[editor]
# show a ruler at column 120
rulers = [80, 120]
# use relative line numbers
line-number = "relative"
mouse = false
# force the theme to show colors
true-color = true
# highlight all lines with a cursor
cursorline = true
# show currently open buffers, only when more than one exists
bufferline = "multiple"

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

# quick auto completion trigger
# completion-trigger-len = 1
# when enter to the struct fields, immediately suggests fields
completion-trigger-len = 0
idle-timeout = 0 

# [editor.file-picker]
# hidden = false

[keys.insert]
C-space = "completion"
# not work
# "{" = ["insert_char", "{", "completion"]

[keys.normal]
# Space-k-k = "hover"
A-k = "keep_selections"
# minus = "file_picker_in_current_buffer_directory"
# minus = [":o", "<C-r>", "%"]
# create new file
S-n = [":o", "insert_register", "select_all"]
# S-n = ":o %"
# C-x = [":o", "insert_register", "select_all"]
# C-x = ":o <C-r>%"

A-y = "yank_main_selection_to_clipboard"
A-Y = "yank_main_selection_to_clipboard"
A-p = "paste_clipboard_after" 
A-P = "paste_clipboard_before" 
C-f = [":new", ":insert-output lf-pick", "select_all", "split_selection_on_newline", "goto_file", "goto_last_modified_file", ":buffer-close!"]

# [editor.clippy]
# line = true
# line-number-mode = "compact"

[editor.lsp]
# disable automatically popups of signature parameter help
auto-signature-help = true
# show lsp messages in the status line
display-messages = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
